# Generated by Django 4.2.30 on 2026-04-26 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='merchant',
            field=models.OneToOneField(limit_choices_to={'role': 'merchant'}, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='reviewer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'reviewer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together={('submission', 'doc_type')},
        ),
    ]
